/* core.js — 기초 영단어 + 한글 뜻, 그리고 차단 목록   [자동 생성: _source/build_core.py]

   쓰임새 셋
     1) AI 견습 난이도의 단어 풀 — AI가 zygodactylous 같은 걸 내면 학습도 재미도 없다
     2) 힌트·전적 화면의 한글 뜻 — Englknight의 교육 축. 16만 개에 뜻을 달 방법은 없다
     3) 판정 사전의 일부 (dict.js + extra.js + core.js 를 하나의 Set으로 합친다)

   수록 1443개. 전량 dict.js와 대조해 **사전 미수록 0 · 중복 0 · 형식 위반 0** 확인.
   글자별 커버리지를 의도적으로 배분했다 — AI가 어느 글자를 받아도 답할 수 있어야 한다.
   x가 5개뿐인 것은 영어 자체의 한계다(학습자가 쓸 x 단어가 그것뿐).
   구제 글자 규칙(SPEC §4.3)이 받는다.

   형식: "단어|뜻" 을 줄바꿈으로 이었다. 뜻에 | 와 따옴표가 없음을 굽는 시점에 검증한다.

   ── BLOCK: 차단 목록 103개 ──
   dict.js의 원본 ENABLE에는 욕설·비속어·차별어가 그대로 들어 있다. 사이트가 공개 배포되고
   어린 사용자도 있으므로 판정 규칙 ⑥에서 막는다.
   ⚠ **AI 단어 풀에서도 반드시 제외한다.** 기사·검성 난이도는 넓은 풀을 쓰므로
      거르지 않으면 AI가 욕설을 낸다. 이게 차단 목록의 더 중요한 쓰임이다.
*/
(function(){
"use strict";
var PAIRS=[
"able|할 수 있는","about|~에 대하여","above|~위에","accept|받아들이다","accident|사고","ache|아프다",
"across|가로질러","act|행동하다","actor|배우","add|더하다","address|주소","adult|어른","advice|충고",
"afraid|두려운","after|~후에","afternoon|오후","again|다시","age|나이","agree|동의하다","air|공기",
"airplane|비행기","airport|공항","alarm|경보","album|앨범","alive|살아 있는","allow|허락하다","almost|거의",
"alone|혼자","along|~을 따라","alphabet|알파벳","already|이미","also|또한","always|항상","ambulance|구급차",
"among|~사이에","ancient|고대의","angel|천사","anger|분노","angle|각도","angry|화난","animal|동물",
"ankle|발목","announce|알리다","answer|대답","ant|개미","apart|떨어져","apartment|아파트","apologize|사과하다",
"appear|나타나다","appetite|식욕","apple|사과","apply|지원하다","area|지역","arm|팔","army|군대",
"around|주위에","arrive|도착하다","arrow|화살","art|예술","artist|예술가","ask|묻다","asleep|잠든",
"assist|돕다","attack|공격하다","attend|참석하다","attention|주의","audience|청중","aunt|이모","author|작가",
"autumn|가을","avenue|대로","average|평균","avoid|피하다","awake|깨어 있는","award|상","aware|알고 있는",
"away|떨어져","baby|아기","back|등","bag|가방","bake|굽다","ball|공","balloon|풍선","banana|바나나",
"band|악단","bank|은행","bark|짖다","basket|바구니","bath|목욕","beach|해변","bean|콩","bear|곰",
"beard|턱수염","beautiful|아름다운","because|왜냐하면","become|되다","bed|침대","bee|벌","beef|소고기",
"before|~전에","begin|시작하다","behind|뒤에","believe|믿다","bell|종","belong|속하다","below|아래에",
"belt|허리띠","bench|긴 의자","beside|옆에","between|사이에","bicycle|자전거","big|큰","bird|새",
"birthday|생일","bite|물다","bitter|쓴","black|검은","blanket|담요","blind|눈먼","block|막다","blood|피",
"blow|불다","blue|파란","board|판자","boat|배","body|몸","boil|끓이다","bone|뼈","book|책","boot|장화",
"border|국경","borrow|빌리다","bottle|병","bottom|바닥","bowl|그릇","box|상자","boy|소년","brain|뇌",
"branch|가지","brave|용감한","bread|빵","break|깨다","breakfast|아침 식사","breathe|숨쉬다","bridge|다리",
"bright|밝은","bring|가져오다","broom|빗자루","brother|형제","brown|갈색의","brush|솔","bubble|거품",
"bucket|양동이","build|짓다","burn|타다","bury|묻다","bus|버스","bush|덤불","busy|바쁜","butter|버터",
"button|단추","buy|사다","cabbage|양배추","cage|새장","cake|케이크","calendar|달력","call|부르다","calm|차분한",
"camel|낙타","camera|사진기","camp|야영하다","candle|양초","candy|사탕","cap|모자","captain|선장","car|자동차",
"card|카드","care|돌보다","carpet|양탄자","carrot|당근","carry|나르다","cart|수레","castle|성","cat|고양이",
"catch|잡다","cave|동굴","ceiling|천장","celebrate|축하하다","cell|세포","center|중심","century|세기",
"chain|사슬","chair|의자","chalk|분필","chance|기회","change|바꾸다","cheap|싼","cheek|뺨","cheese|치즈",
"chest|가슴","chicken|닭","child|아이","chin|턱","chocolate|초콜릿","choose|고르다","church|교회",
"circle|원","city|도시","clap|박수치다","class|수업","clean|깨끗한","clear|맑은","clever|영리한","climb|오르다",
"clock|시계","close|닫다","cloth|천","cloud|구름","clown|광대","coach|감독","coast|해안","coat|외투",
"coffee|커피","coin|동전","cold|추운","collect|모으다","color|색","comb|빗","come|오다","comfort|위로하다",
"common|흔한","compare|비교하다","complete|완성하다","computer|컴퓨터","cook|요리하다","cool|시원한","copy|베끼다",
"corn|옥수수","corner|모퉁이","correct|옳은","cost|값이 들다","cotton|목화","cough|기침하다","count|세다",
"country|나라","couple|한 쌍","courage|용기","course|과정","cousin|사촌","cover|덮다","cow|소",
"crack|금이 가다","crane|두루미","crash|충돌하다","crawl|기다","crayon|크레용","crazy|미친","cream|크림",
"create|창조하다","cross|건너다","crowd|군중","crown|왕관","cruel|잔인한","cry|울다","cup|컵",
"curious|호기심 많은","curtain|커튼","curve|곡선","cushion|방석","customer|손님","cut|자르다","cute|귀여운",
"dad|아빠","daily|날마다의","damage|손해","dance|춤추다","danger|위험","dark|어두운","date|날짜","daughter|딸",
"dawn|새벽","day|날","dead|죽은","deaf|귀먹은","deal|거래","dear|친애하는","death|죽음","decide|결정하다",
"deep|깊은","deer|사슴","delay|미루다","delicious|맛있는","deliver|배달하다","dentist|치과의사","depend|의지하다",
"describe|묘사하다","desert|사막","design|설계하다","desk|책상","dessert|후식","destroy|파괴하다",
"develop|발전시키다","diamond|다이아몬드","diary|일기","dictionary|사전","die|죽다","different|다른",
"difficult|어려운","dig|파다","dinner|저녁 식사","direct|직접의","dirty|더러운","disappear|사라지다",
"discover|발견하다","disease|질병","dish|접시","distance|거리","divide|나누다","doctor|의사","dog|개",
"doll|인형","dollar|달러","donkey|당나귀","door|문","double|두 배의","doubt|의심하다","draw|그리다","dream|꿈",
"dress|옷","drink|마시다","drive|운전하다","drop|떨어뜨리다","drum|북","dry|마른","duck|오리","dust|먼지",
"duty|의무","each|각각의","eagle|독수리","ear|귀","early|이른","earn|벌다","earth|지구","east|동쪽",
"easy|쉬운","eat|먹다","edge|가장자리","education|교육","effort|노력","egg|달걀","eight|여덟",
"either|둘 중 하나","elbow|팔꿈치","elephant|코끼리","elevator|승강기","else|다른","empty|빈","end|끝",
"enemy|적","energy|에너지","engine|엔진","enjoy|즐기다","enough|충분한","enter|들어가다","envelope|봉투",
"equal|같은","escape|달아나다","evening|저녁","event|사건","ever|언젠가","every|모든","exact|정확한",
"example|보기","excellent|훌륭한","except|~을 제외하고","exchange|교환하다","excited|신이 난","excuse|용서하다",
"exercise|운동","exit|출구","expect|기대하다","expensive|비싼","explain|설명하다","explore|탐험하다","eye|눈",
"face|얼굴","fact|사실","factory|공장","fail|실패하다","fair|공정한","fall|떨어지다","false|거짓의","family|가족",
"famous|유명한","fan|선풍기","far|먼","farm|농장","fast|빠른","fat|뚱뚱한","father|아버지","fault|잘못",
"favorite|가장 좋아하는","fear|두려움","feather|깃털","feed|먹이다","feel|느끼다","fence|울타리","festival|축제",
"fever|열","few|몇 안 되는","field|들판","fight|싸우다","fill|채우다","film|영화","find|찾다","fine|좋은",
"finger|손가락","finish|끝내다","fire|불","fish|물고기","fist|주먹","fit|맞다","fix|고치다","flag|깃발",
"flame|불꽃","flat|평평한","float|뜨다","floor|바닥","flour|밀가루","flower|꽃","fly|날다","fog|안개",
"fold|접다","follow|따르다","food|음식","fool|바보","foot|발","football|축구","force|힘","forest|숲",
"forget|잊다","forgive|용서하다","fork|포크","form|형태","forward|앞으로","fountain|분수","fox|여우",
"frame|틀","free|자유로운","fresh|신선한","friend|친구","frighten|겁주다","frog|개구리","front|앞",
"fruit|과일","fry|튀기다","full|가득 찬","fun|재미","funny|우스운","fur|털","furniture|가구","future|미래",
"game|놀이","garage|차고","garden|정원","gas|기체","gate|문","gather|모으다","gentle|온화한","gift|선물",
"giraffe|기린","girl|소녀","give|주다","glad|기쁜","glass|유리","glove|장갑","glue|풀","goal|목표",
"goat|염소","gold|금","good|좋은","goose|거위","grade|등급","grain|곡물","grandmother|할머니","grape|포도",
"grass|풀","gray|회색의","great|위대한","green|초록의","greet|인사하다","ground|땅","group|무리","grow|자라다",
"guard|지키다","guess|추측하다","guest|손님","guide|안내하다","guitar|기타","gun|총","habit|습관","hair|머리카락",
"half|절반","hall|복도","hammer|망치","hand|손","handsome|잘생긴","hang|걸다","happen|일어나다","happy|행복한",
"harbor|항구","hard|단단한","harvest|수확","hat|모자","hate|미워하다","head|머리","health|건강","hear|듣다",
"heart|심장","heat|열","heavy|무거운","heel|발꿈치","height|높이","help|돕다","hen|암탉","hero|영웅",
"hide|숨다","high|높은","hill|언덕","history|역사","hit|치다","hobby|취미","hold|잡다","hole|구멍",
"holiday|휴일","home|집","honest|정직한","honey|꿀","hope|희망","horse|말","hospital|병원","hot|뜨거운",
"hotel|호텔","hour|시간","house|집","however|그러나","huge|거대한","human|인간","hundred|백","hungry|배고픈",
"hunt|사냥하다","hurry|서두르다","hurt|다치게 하다","husband|남편","ice|얼음","idea|생각","important|중요한",
"improve|나아지다","include|포함하다","increase|늘리다","indeed|정말로","industry|산업","information|정보",
"injure|다치게 하다","ink|잉크","insect|곤충","inside|안쪽","instead|대신에","interest|흥미",
"introduce|소개하다","invent|발명하다","invite|초대하다","iron|철","island|섬","jacket|재킷","jail|감옥",
"jam|잼","jar|병","jaw|턱","jazz|재즈","jealous|질투하는","jeans|청바지","jelly|젤리","jewel|보석","job|일",
"join|합치다","joke|농담","journey|여행","joy|기쁨","judge|판사","juice|주스","jump|뛰다","jungle|정글",
"junior|손아래의","just|단지","keep|지키다","kettle|주전자","key|열쇠","kick|차다","kill|죽이다","kind|친절한",
"king|왕","kiss|입맞춤","kitchen|부엌","kite|연","knee|무릎","knife|칼","knock|두드리다","knot|매듭",
"know|알다","lack|부족","ladder|사다리","lady|숙녀","lake|호수","lamb|새끼 양","lamp|등불","land|땅",
"language|언어","large|큰","last|마지막의","late|늦은","laugh|웃다","law|법","lazy|게으른","lead|이끌다",
"leaf|잎","learn|배우다","leather|가죽","leave|떠나다","left|왼쪽","leg|다리","lemon|레몬","lend|빌려주다",
"length|길이","lesson|수업","letter|편지","level|수준","library|도서관","lie|거짓말","life|삶",
"lift|들어올리다","light|빛","like|좋아하다","limit|한계","line|줄","lion|사자","lip|입술","liquid|액체",
"list|목록","listen|듣다","little|작은","live|살다","load|짐","local|지역의","lock|잠그다","lonely|외로운",
"long|긴","look|보다","lose|잃다","loud|시끄러운","love|사랑","low|낮은","luck|운","lunch|점심","lung|폐",
"machine|기계","mad|미친","magazine|잡지","magic|마술","mail|우편","main|주된","make|만들다","man|남자",
"manage|다루다","many|많은","map|지도","march|행진하다","mark|표시","market|시장","marry|결혼하다","match|성냥",
"material|재료","matter|문제","maybe|아마도","meal|식사","mean|의미하다","measure|재다","meat|고기",
"medicine|약","meet|만나다","melon|멜론","melt|녹다","member|회원","memory|기억","mend|고치다",
"message|소식","metal|금속","method|방법","middle|가운데","midnight|자정","mild|온화한","milk|우유",
"mind|마음","mine|나의 것","minute|분","mirror|거울","miss|그리워하다","mistake|실수","mix|섞다","model|모형",
"modern|현대의","moment|순간","money|돈","monkey|원숭이","month|달","moon|달","morning|아침",
"mosquito|모기","mother|어머니","motor|발동기","mountain|산","mouse|쥐","mouth|입","move|움직이다",
"movie|영화","much|많은","mud|진흙","museum|박물관","mushroom|버섯","music|음악","must|해야 한다","nail|못",
"name|이름","narrow|좁은","nation|나라","nature|자연","near|가까운","neat|깔끔한","neck|목","need|필요하다",
"needle|바늘","neighbor|이웃","nephew|조카","nest|둥지","net|그물","never|결코","new|새로운","news|소식",
"newspaper|신문","next|다음의","nice|좋은","niece|조카딸","night|밤","nine|아홉","noble|고귀한","noise|소음",
"none|아무도","noodle|국수","noon|정오","north|북쪽","nose|코","note|쪽지","nothing|아무것도",
"notice|알아차리다","novel|소설","now|지금","number|숫자","nurse|간호사","nut|견과","obey|따르다","object|물건",
"ocean|바다","offer|제안하다","office|사무실","often|자주","oil|기름","old|늙은","olive|올리브","once|한 번",
"onion|양파","only|오직","open|열다","opinion|의견","orange|오렌지","order|주문하다","ordinary|평범한",
"other|다른","ought|해야 한다","ours|우리 것","outside|바깥","oven|오븐","over|위에","owe|빚지다","owl|올빼미",
"own|소유하다","oxygen|산소","oyster|굴","pack|싸다","page|쪽","pain|고통","paint|칠하다","pair|한 쌍",
"palace|궁전","pale|창백한","palm|손바닥","pan|냄비","paper|종이","parent|부모","park|공원","parrot|앵무새",
"part|부분","partner|동반자","party|잔치","pass|지나가다","passenger|승객","past|과거","path|길",
"patient|참을성 있는","pattern|무늬","pay|지불하다","peace|평화","peach|복숭아","pear|배","pearl|진주","pen|펜",
"pencil|연필","people|사람들","pepper|후추","perfect|완벽한","perhaps|아마도","period|기간","person|사람",
"pet|애완동물","photograph|사진","piano|피아노","pick|고르다","picnic|소풍","picture|그림","pie|파이",
"piece|조각","pig|돼지","pigeon|비둘기","pile|더미","pillow|베개","pilot|조종사","pin|핀","pine|소나무",
"pink|분홍의","pipe|관","place|장소","plain|평범한","plan|계획","plane|비행기","plant|식물","plastic|플라스틱",
"plate|접시","play|놀다","pleasant|즐거운","please|기쁘게 하다","plenty|풍부함","pocket|주머니","poem|시",
"point|점","poison|독","police|경찰","polite|예의 바른","pond|연못","pool|웅덩이","poor|가난한",
"popular|인기 있는","port|항구","possible|가능한","post|우편","pot|냄비","potato|감자","pour|붓다",
"powder|가루","power|힘","practice|연습","praise|칭찬하다","pray|기도하다","prepare|준비하다","present|선물",
"president|대통령","press|누르다","pretty|예쁜","prevent|막다","price|값","pride|자부심","prince|왕자",
"print|인쇄하다","prison|감옥","prize|상","problem|문제","produce|생산하다","promise|약속","protect|보호하다",
"proud|자랑스러운","prove|증명하다","public|공공의","pull|당기다","pump|펌프","punish|벌하다","pupil|학생",
"puppy|강아지","pure|순수한","purple|보라색의","purpose|목적","purse|지갑","push|밀다","puzzle|수수께끼",
"quality|품질","quantity|양","quarrel|다투다","quarter|사분의 일","queen|여왕","question|질문","queue|줄",
"quick|빠른","quiet|조용한","quit|그만두다","quite|꽤","quiz|쪽지 시험","rabbit|토끼","race|경주","radio|라디오",
"rail|철로","rain|비","rainbow|무지개","raise|올리다","rat|쥐","reach|닿다","read|읽다","ready|준비된",
"real|진짜의","reason|이유","receive|받다","record|기록","red|빨간","refuse|거절하다","remember|기억하다",
"remove|치우다","repair|고치다","repeat|되풀이하다","reply|대답하다","report|보고하다","rescue|구조하다","rest|쉬다",
"restaurant|식당","result|결과","return|돌아오다","rice|쌀","rich|부유한","ride|타다","right|오른쪽",
"ring|반지","ripe|익은","rise|오르다","river|강","road|길","rob|훔치다","rock|바위","rocket|로켓",
"roll|구르다","roof|지붕","room|방","root|뿌리","rope|밧줄","rose|장미","rough|거친","round|둥근","row|줄",
"rub|문지르다","rubber|고무","rude|무례한","rule|규칙","run|달리다","rush|서두르다","sad|슬픈","safe|안전한",
"sail|항해하다","salt|소금","same|같은","sand|모래","save|구하다","say|말하다","scale|저울","school|학교",
"science|과학","scissors|가위","score|점수","scream|비명 지르다","sea|바다","search|찾다","season|계절",
"seat|자리","second|두 번째의","secret|비밀","see|보다","seed|씨앗","seem|~처럼 보이다","sell|팔다","send|보내다",
"sense|감각","sentence|문장","serious|진지한","serve|제공하다","seven|일곱","several|몇몇의","sew|바느질하다",
"shade|그늘","shadow|그림자","shake|흔들다","shall|~할 것이다","shame|부끄러움","shape|모양","share|나누다",
"sharp|날카로운","sheep|양","sheet|장","shelf|선반","shell|껍질","shine|빛나다","ship|배","shirt|셔츠",
"shoe|신발","shoot|쏘다","shop|가게","short|짧은","shoulder|어깨","shout|외치다","show|보여주다",
"shower|소나기","shut|닫다","shy|수줍은","sick|아픈","side|쪽","sight|시야","sign|표지","silent|조용한",
"silk|비단","silver|은","simple|간단한","since|~이후로","sing|노래하다","single|하나의","sink|가라앉다",
"sister|자매","sit|앉다","six|여섯","size|크기","skate|스케이트를 타다","ski|스키를 타다","skin|피부","skirt|치마",
"sky|하늘","sleep|자다","slide|미끄러지다","slow|느린","small|작은","smart|똑똑한","smell|냄새","smile|미소",
"smoke|연기","snake|뱀","snow|눈","soap|비누","soft|부드러운","soil|흙","soldier|군인","solve|풀다",
"some|약간의","son|아들","song|노래","soon|곧","sorry|미안한","sound|소리","soup|수프","sour|신","south|남쪽",
"space|공간","speak|말하다","speed|속도","spell|철자를 쓰다","spend|쓰다","spider|거미","spoon|숟가락",
"sport|운동","spot|점","spread|펴다","spring|봄","square|정사각형","stairs|계단","stamp|우표","stand|서다",
"star|별","start|시작하다","station|역","stay|머무르다","steal|훔치다","steam|증기","steel|강철","step|걸음",
"stick|막대기","still|여전히","stomach|위","stone|돌","stop|멈추다","store|가게","storm|폭풍","story|이야기",
"straight|곧은","strange|이상한","straw|빨대","street|거리","strong|강한","student|학생","study|공부하다",
"stupid|어리석은","subject|주제","subway|지하철","sugar|설탕","suit|정장","summer|여름","sun|해",
"supper|저녁 식사","support|지지하다","suppose|가정하다","sure|확실한","surprise|놀라게 하다","sweater|스웨터",
"sweep|쓸다","sweet|달콤한","swim|수영하다","sword|칼","table|탁자","tail|꼬리","tailor|재단사","take|가지다",
"talk|말하다","tall|키 큰","tape|테이프","taste|맛","taxi|택시","tea|차","teach|가르치다","team|팀",
"tear|눈물","teeth|이빨","telephone|전화","television|텔레비전","tell|말하다","temple|절","ten|열",
"tent|천막","terrible|끔찍한","test|시험","than|~보다","thank|감사하다","theater|극장","thick|두꺼운",
"thief|도둑","thin|얇은","thing|것","think|생각하다","thirsty|목마른","thread|실","throat|목구멍",
"throw|던지다","thumb|엄지","thunder|천둥","ticket|표","tide|조수","tidy|정돈된","tie|묶다","tiger|호랑이",
"time|시간","tiny|아주 작은","tired|피곤한","today|오늘","toe|발가락","together|함께","tomato|토마토",
"tomorrow|내일","tongue|혀","tonight|오늘 밤","tool|도구","tooth|이","top|꼭대기","touch|만지다","tour|여행",
"towel|수건","tower|탑","town|마을","toy|장난감","track|자취","trade|무역","traffic|교통","train|기차",
"travel|여행하다","tray|쟁반","treasure|보물","tree|나무","triangle|삼각형","trick|속임수","trip|여행",
"trouble|곤란","truck|트럭","true|참된","trust|믿다","truth|진실","try|해보다","tube|관","tunnel|터널",
"turn|돌다","turtle|거북","twice|두 번","twin|쌍둥이","type|종류","ugly|못생긴","umbrella|우산","uncle|삼촌",
"under|아래에","understand|이해하다","uniform|제복","union|연합","unit|단위","universe|우주",
"university|대학","until|~까지","upon|~위에","upper|위쪽의","upset|속상한","use|쓰다","useful|쓸모 있는",
"usual|보통의","vacation|방학","valley|골짜기","value|가치","various|여러 가지의","vase|꽃병","vegetable|채소",
"vehicle|탈것","very|매우","victory|승리","video|영상","view|경치","village|마을","violin|바이올린",
"visit|방문하다","voice|목소리","volcano|화산","vote|투표하다","voyage|항해","wait|기다리다","wake|깨다",
"walk|걷다","wall|벽","wallet|지갑","want|원하다","war|전쟁","warm|따뜻한","warn|경고하다","wash|씻다",
"waste|낭비하다","watch|보다","water|물","wave|물결","way|길","weak|약한","wealth|부","wear|입다",
"weather|날씨","wedding|결혼식","week|주","weight|무게","welcome|환영하다","well|잘","west|서쪽","wet|젖은",
"whale|고래","wheat|밀","wheel|바퀴","while|~하는 동안","whisper|속삭이다","whistle|휘파람","white|흰",
"whole|전체의","wide|넓은","wife|아내","wild|야생의","will|~할 것이다","win|이기다","wind|바람","window|창문",
"wine|포도주","wing|날개","winter|겨울","wipe|닦다","wire|철사","wise|현명한","wish|바라다","witch|마녀",
"without|~없이","wolf|늑대","woman|여자","wonder|궁금해하다","wood|나무","wool|양털","word|낱말","work|일하다",
"world|세계","worm|벌레","worry|걱정하다","worse|더 나쁜","worth|가치 있는","wound|상처","wrap|싸다",
"wrist|손목","write|쓰다","wrong|틀린","xenon|제논","xerox|복사하다","xylem|물관부","xylophone|실로폰",
"yacht|요트","yak|야크","yam|마","yard|마당","yarn|실","yawn|하품하다","year|해","yearn|그리워하다",
"yeast|효모","yell|소리치다","yellow|노란","yes|네","yesterday|어제","yet|아직","yield|내주다","yoga|요가",
"yogurt|요구르트","yoke|멍에","yolk|노른자","young|젊은","your|너의","youth|젊음","zebra|얼룩말","zero|영",
"zinc|아연","zip|잠그다","zipper|지퍼","zone|구역","zoo|동물원","zoom|확대하다","zigzag|지그재그","zeal|열의",
"zenith|절정","zodiac|황도대","zombie|좀비","zoology|동물학","xebec|세돛 범선","yelp|깽깽거리다","yonder|저쪽의",
"youngster|젊은이","yourself|너 자신","yeoman|자작농","yardstick|잣대","yearbook|졸업 앨범","kangaroo|캥거루",
"keen|예리한","kennel|개집","kernel|알맹이","kidney|콩팥","kingdom|왕국","kiwi|키위","knight|기사",
"knowledge|지식","koala|코알라","kindergarten|유치원","kidnap|납치하다","ketchup|케첩","umpire|심판",
"unable|할 수 없는","uncover|밝히다","unfair|불공평한","unhappy|불행한","unite|연합하다","unknown|알려지지 않은",
"unless|~하지 않으면","unusual|평범하지 않은","upstairs|위층","urban|도시의","urgent|긴급한","useless|쓸모없는",
"upward|위쪽으로","utensil|기구","vacuum|진공","vain|헛된","valid|유효한","vanish|사라지다","variety|다양성",
"vast|광대한","veil|너울","velvet|벨벳","verb|동사","vest|조끼","victim|피해자","violet|제비꽃","virus|바이러스",
"visible|보이는","vision|시력","visitor|방문객","vivid|생생한","volume|부피","ideal|이상적인","idle|게으른",
"image|모습","imagine|상상하다","imitate|흉내내다","immediate|즉각적인","impossible|불가능한","income|소득",
"indoor|실내의","infant|유아","inform|알리다","injury|부상","insist|고집하다","instant|즉시의",
"instrument|악기","intelligent|똑똑한","intend|의도하다","interview|면접","invitation|초대장",
"involve|포함하다","item|항목","itself|그 자체","quest|탐구","quiver|떨다","quote|인용하다",
"qualify|자격을 갖추다","quaint|고풍스러운","quench|갈증을 풀다"
];

var BLOCK=[
"anal","anus","arse","arses","asshole","assholes","bastard","bastards","bestiality","bitch",
"bitched","bitches","bitching","bollocks","boobs","chink","chinks","cocaine","cock","cocks",
"crap","crappy","craps","cripple","crippled","cunt","cunts","damn","damned","dick","dicks",
"dyke","dykes","fag","faggot","faggots","fags","fuck","fucked","fucker","fuckers","fucking",
"fucks","goddamn","gook","gooks","hell","heroin","horny","incest","kike","kikes",
"masturbate","masturbated","masturbation","meth","nigger","niggers","orgasm","orgasms",
"penis","penises","pimp","pimps","piss","pissed","pissing","porn","porno","pornography",
"prick","pricks","rape","raped","raping","rapist","rapists","retard","retarded","retards",
"semen","shit","shits","shitted","shitting","shitty","slut","sluts","sodomize","sodomy",
"sperm","spic","spics","suicide","tits","titties","vagina","vaginas","whore","whores",
"whoring","wop","wops"
];

var WORDS=[], MEAN={};
for(var i=0;i<PAIRS.length;i++){
  var p=PAIRS[i], k=p.indexOf("|"), w=p.slice(0,k);
  WORDS.push(w); MEAN[w]=p.slice(k+1);
}
window.WB_CORE={ WORDS:WORDS, MEAN:MEAN, BLOCK:BLOCK };
})();
